/**
 * Os quatro lugares que descrevem um alerta não podem divergir.
 *
 * `lib/api-spec/openapi.yaml`, `lib/api-zod`, `lib/api-client-react` e
 * `lib/db/src/schema` carregam cabeçalho "Generated by orval — do not edit
 * manually", mas neste repo **nenhum gerador roda**: os quatro são mantidos à
 * mão. O efeito é que adicionar uma coluna e esquecer um dos contratos não
 * falha em lugar nenhum -- o campo simplesmente não chega à tela, e o typecheck
 * fica limpo porque os tipos também foram escritos à mão.
 *
 * Este teste é o gerador que não existe, invertido: em vez de produzir os
 * arquivos, confere que eles concordam. Ele lê os quatro como TEXTO de
 * propósito, porque é assim que eles são mantidos.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { join } from "path";
// `@workspace/db/schema` e não `@workspace/db`: o index do pacote abre a conexão
// e exige DATABASE_URL, e este teste só quer a DECLARAÇÃO das tabelas.
import { alertsTable, alertFiringsTable } from "@workspace/db/schema";
import { INDICADORES_DE_CONDICAO } from "@workspace/alertas";

const RAIZ = join(__dirname, "../../../..");
const ler = (p: string) => readFileSync(join(RAIZ, p), "utf-8");

const OPENAPI = ler("lib/api-spec/openapi.yaml");
const ZOD_RUNTIME = ler("lib/api-zod/src/generated/api.ts");
const ZOD_TIPOS = ler("lib/api-zod/src/generated/types/priceAlert.ts");
const CLIENT = ler("lib/api-client-react/src/generated/api.schemas.ts");

/**
 * Colunas que existem só no servidor e não fazem parte do contrato HTTP.
 *
 * `userId` é o dono (a rota filtra por ele, nunca o devolve); `updatedAt` não é
 * exposto em nenhum recurso desta API. `enableRLS` não é coluna: é método que o
 * drizzle pendura no objeto da tabela.
 */
const SO_NO_SERVIDOR = new Set(["userId", "updatedAt", "enableRLS"]);

function blocoOpenapi(nome: string): string {
  // Os schemas do openapi.yaml vivem com 4 espaços de recuo. O bloco vai do
  // `    Nome:` até o próximo schema irmão -- `\n    ` sozinho não serve como
  // delimitador, porque toda linha interna também começa com quatro espaços.
  const inicio = OPENAPI.indexOf(`    ${nome}:\n`);
  expect(inicio, `${nome} não existe no openapi.yaml`).toBeGreaterThan(-1);
  const resto = OPENAPI.slice(inicio + 1);
  const proximo = resto.search(/\n {4}[A-Za-z][A-Za-z0-9]*:\n/);
  return proximo > -1 ? resto.slice(0, proximo) : resto;
}

function camposDoBlocoOpenapi(nome: string): Set<string> {
  const bloco = blocoOpenapi(nome);
  const props = bloco.slice(bloco.indexOf("properties:"));
  return new Set(
    [...props.matchAll(/^ {8}([A-Za-z][A-Za-z0-9]*):/gm)].map((m) => m[1]),
  );
}

/** O corpo de um `export const X = zod.object({ ... })` em api.ts. */
function objetoZod(nome: string): string {
  const inicio = ZOD_RUNTIME.indexOf(`export const ${nome} = zod.object({`);
  expect(inicio, `${nome} não existe em api-zod/src/generated/api.ts`)
    .toBeGreaterThan(-1);
  const resto = ZOD_RUNTIME.slice(inicio);
  return resto.slice(0, resto.indexOf("\n})"));
}

describe("alerts: schema do banco x contrato HTTP", () => {
  it("toda coluna de `alerts` está no PriceAlert do openapi", () => {
    const doBanco = Object.keys(alertsTable)
      .filter((k) => !SO_NO_SERVIDOR.has(k));
    const doContrato = camposDoBlocoOpenapi("PriceAlert");
    const faltando = doBanco.filter((c) => !doContrato.has(c));
    expect(faltando, "colunas sem contrato — a tela nunca vai vê-las").toEqual([]);
  });

  it("toda coluna de `alert_firings` está no AlertFiring do openapi", () => {
    const doBanco = Object.keys(alertFiringsTable)
      .filter((k) => !SO_NO_SERVIDOR.has(k));
    const doContrato = camposDoBlocoOpenapi("AlertFiring");
    expect(doBanco.filter((c) => !doContrato.has(c))).toEqual([]);
  });
});

describe("alerts: os quatro contratos concordam", () => {
  // Os campos da parte 2 do alerta composto. A lista é explícita e não derivada
  // do banco de propósito: derivá-la faria o teste passar a concordar com
  // qualquer coisa que o schema dissesse, e o ponto é justamente amarrar estes.
  const CAMPOS_NOVOS = ["conditions", "confirmAtClose", "fireOnce", "note"];

  it.each(CAMPOS_NOVOS)("%s existe nos quatro", (campo) => {
    expect(camposDoBlocoOpenapi("PriceAlert").has(campo)).toBe(true);
    expect(ZOD_RUNTIME).toContain(`"${campo}"`);
    expect(ZOD_TIPOS).toContain(campo);
    expect(CLIENT).toContain(campo);
  });

  it("o enum de indicadores é o mesmo em todos os lugares que o escrevem", () => {
    // Um indicador a mais no avaliador e a menos no contrato dá 400 na criação
    // de um alerta que o motor sabe avaliar -- falha que só aparece em produção,
    // porque nada no código liga as duas listas.
    const doAvaliador = INDICADORES_DE_CONDICAO;
    const doOpenapi = blocoOpenapi("AlertCondition");
    const doZod = objetoZod("AlertConditionSchema");
    for (const ind of doAvaliador) {
      expect(doOpenapi, `${ind} falta no openapi`).toContain(ind);
      expect(doZod, `${ind} falta no zod`).toContain(`"${ind}"`);
      expect(CLIENT, `${ind} falta no client React`).toContain(`${ind}: '${ind}'`);
    }
    // E o contrário: nada no contrato que o avaliador não saiba avaliar.
    const noZod = [...doZod.matchAll(/"([A-Za-z0-9]+)"/g)].map((m) => m[1])
      .filter((v) => !["indicator", "op", "value"].includes(v)
        && !["above", "below"].includes(v));
    expect(noZod.filter((v) => !doAvaliador.includes(v as never))).toEqual([]);
  });

  it("os DOIS objetos de alerta no zod de runtime ganharam os campos juntos", () => {
    // `ListAlertsResponseItem` e `ToggleAlertResponse` descrevem a MESMA linha e
    // são dois objetos copiados lado a lado. Atualizar um só faz o PATCH
    // devolver um alerta sem os campos novos, e a tela sobrescrever o estado
    // local com isso -- o toggle "apagaria" as condições na interface.
    for (const objeto of ["ListAlertsResponseItem", "ToggleAlertResponse"]) {
      const corpo = objetoZod(objeto);
      for (const campo of CAMPOS_NOVOS) {
        expect(corpo, `${campo} falta em ${objeto}`).toContain(`"${campo}"`);
      }
    }
  });

  it("o corpo de criação aceita os campos novos", () => {
    const corpo = objetoZod("CreateAlertBody");
    for (const campo of CAMPOS_NOVOS) {
      expect(corpo, `${campo} falta em CreateAlertBody`).toContain(`"${campo}"`);
    }
  });
});

describe("alerts: a migração e o ensure-schema dizem o mesmo", () => {
  const MIGRACAO = ler("lib/db/migrations/0039_alerts_condicoes_multiplas.sql");
  const ENSURE = ler("artifacts/api-server/src/lib/ensure-schema.ts");

  it("cada coluna da migração também está no ensure-schema", () => {
    // O `ensure-schema` existe porque o boot não pode depender de `db push` ter
    // rodado. Uma coluna só na migração aparece em produção como erro de query
    // num contêiner recém-subido.
    const colunas = [...MIGRACAO.matchAll(/ADD COLUMN IF NOT EXISTS (\w+)/g)]
      .map((m) => m[1]);
    expect(colunas.length).toBeGreaterThanOrEqual(5);
    for (const c of colunas) {
      expect(ENSURE, `${c} está na migração mas não no ensure-schema`)
        .toContain(`ADD COLUMN IF NOT EXISTS ${c}`);
    }
  });

  it("conditions entra com default vazio, não com backfill", () => {
    // Backfill em SQL exigiria reimplementar a precedência de threshold_price
    // sobre threshold_pct -- terceira cópia de uma regra que já quebrou com
    // duas. A conversão é na leitura (condicoesDoAlerta).
    expect(MIGRACAO).toContain("conditions jsonb NOT NULL DEFAULT '[]'::jsonb");
    expect(MIGRACAO).not.toMatch(/UPDATE\s+alerts/i);
  });
});
